import Link from 'next/link'
import { Shield } from 'lucide-react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms & Conditions | CricketTips.ai',
  description: 'Terms and Conditions for using CricketTips.ai — AI cricket predictions, affiliate content, and responsible gambling.',
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-white font-bold text-lg mb-3 pb-2 border-b border-gray-800">{title}</h2>
      <div className="text-gray-400 text-sm leading-relaxed space-y-3">{children}</div>
    </section>
  )
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-950">
      <div className="max-w-3xl mx-auto px-4 py-12">

        {/* Header */}
        <div className="mb-10">
          <div className="flex items-center gap-2 mb-4">
            <Shield className="w-5 h-5 text-emerald-400" />
            <Link href="/" className="text-gray-500 text-sm hover:text-white transition-colors">CricketTips.ai</Link>
            <span className="text-gray-700">/</span>
            <span className="text-gray-400 text-sm">Terms & Conditions</span>
          </div>
          <h1 className="text-3xl font-extrabold text-white mb-2">Terms & Conditions</h1>
          <p className="text-gray-500 text-sm">Last updated: 5 July 2026 · Effective date: 5 July 2026</p>
          <div className="mt-4 bg-amber-500/10 border border-amber-500/20 rounded-xl px-4 py-3">
            <p className="text-amber-400 text-xs font-semibold">
              Important: This site is for entertainment purposes only. We do not facilitate or accept bets. You must be 18 or older to use this site.
            </p>
          </div>
        </div>

        <Section title="1. Acceptance of Terms">
          <p>
            By accessing or using CricketTips.ai ("the Site", "we", "us", "our"), you agree to be bound by these Terms & Conditions and our <Link href="/privacy" className="text-emerald-400 hover:text-emerald-300 underline">Privacy Policy</Link>. If you do not agree, you must not use this site.
          </p>
          <p>
            These terms constitute a legally binding agreement between you ("the User") and CricketTips.ai. We reserve the right to update these terms at any time. Continued use of the site after changes are posted constitutes acceptance of the revised terms.
          </p>
        </Section>

        <Section title="2. Eligibility & Age Restriction">
          <p>
            You must be at least <strong className="text-white">18 years of age</strong> to access or use this site. By using CricketTips.ai, you confirm that:
          </p>
          <ul className="list-disc list-inside space-y-2 mt-2 text-gray-500">
            <li>You are 18 years of age or older</li>
            <li>Online gambling or accessing gambling-related content is legal in your jurisdiction</li>
            <li>You are not accessing the site from a restricted territory</li>
          </ul>
          <p className="mt-2">
            We reserve the right to request proof of age at any time and to terminate access for users who do not meet the eligibility requirements.
          </p>
        </Section>

        <Section title="3. Nature of Service">
          <p>
            CricketTips.ai provides AI-generated cricket analysis, match predictions, win probability estimates, and related sports information. All content is provided for <strong className="text-white">entertainment and informational purposes only</strong>.
          </p>
          <ul className="list-disc list-inside space-y-2 mt-2 text-gray-500">
            <li>Our predictions are generated by machine learning algorithms and are not guaranteed to be accurate</li>
            <li>No content on this site constitutes financial, betting, or investment advice</li>
            <li>Past prediction accuracy does not guarantee future results</li>
            <li>We do not accept bets, hold funds, or operate as a bookmaker or betting exchange</li>
            <li>We are not licensed as a gambling operator in any jurisdiction</li>
          </ul>
        </Section>

        <Section title="4. Affiliate Relationships">
          <p>
            CricketTips.ai participates in affiliate marketing programmes. Some links on this site are affiliate links to third-party licensed betting operators. We receive a commission when you register and/or deposit with these operators through our links. This is clearly disclosed where applicable.
          </p>
          <ul className="list-disc list-inside space-y-2 mt-2 text-gray-500">
            <li>Affiliate relationships do not affect the prediction content we provide</li>
            <li>We only partner with operators we believe to be reputable and licensed</li>
            <li>We are not responsible for the terms, conditions, or practices of third-party operators</li>
            <li>Promo codes are subject to the operator's own terms and conditions</li>
            <li>Bonus offers and odds displayed are for illustrative purposes and may change</li>
          </ul>
        </Section>

        <Section title="5. Responsible Gambling">
          <p>
            We are committed to promoting responsible gambling. Gambling should be treated as entertainment, not as a way to make money.
          </p>
          <ul className="list-disc list-inside space-y-2 mt-2 text-gray-500">
            <li>Never bet more than you can afford to lose</li>
            <li>Do not chase losses</li>
            <li>Set deposit and time limits with your operator</li>
            <li>Take regular breaks from gambling</li>
            <li>Seek help if gambling is causing problems in your life</li>
          </ul>
          <p className="mt-3">
            <strong className="text-white">South Africa:</strong> Contact the <strong className="text-white">National Responsible Gambling Programme</strong> — Helpline: <strong className="text-white">0800 006 008</strong> (free, 24/7) or visit <a href="https://www.responsiblegambling.org.za" target="_blank" rel="noopener noreferrer" className="text-emerald-400 underline hover:text-emerald-300">responsiblegambling.org.za</a>
          </p>
          <p>
            <strong className="text-white">United Kingdom:</strong> Contact the <strong className="text-white">National Gambling Helpline (GamCare)</strong> — Helpline: <strong className="text-white">0808 8020 133</strong> (free, 24/7) or visit <a href="https://www.gamcare.org.uk" target="_blank" rel="noopener noreferrer" className="text-emerald-400 underline hover:text-emerald-300">gamcare.org.uk</a>. To self-exclude from all UK-licensed operators, visit <a href="https://www.gamstop.co.uk" target="_blank" rel="noopener noreferrer" className="text-emerald-400 underline hover:text-emerald-300">GAMSTOP.co.uk</a>
          </p>
          <p>
            <strong className="text-white">International:</strong> <a href="https://www.gamblingtherapy.org" target="_blank" rel="noopener noreferrer" className="text-emerald-400 underline hover:text-emerald-300">GamblingTherapy.org</a>
          </p>
        </Section>

        <Section title="6. User Accounts">
          <p>
            When you create an account on CricketTips.ai, you agree to:
          </p>
          <ul className="list-disc list-inside space-y-2 mt-2 text-gray-500">
            <li>Provide accurate and truthful information</li>
            <li>Keep your login credentials confidential</li>
            <li>Be responsible for all activity under your account</li>
            <li>Notify us immediately of any unauthorised use of your account</li>
          </ul>
          <p className="mt-2">
            We reserve the right to suspend or terminate accounts that violate these terms or engage in fraudulent, abusive, or illegal activity.
          </p>
        </Section>

        <Section title="7. Subscriptions & Payments">
          <p>
            CricketTips.ai offers paid subscription plans (Pro and Elite). By subscribing:
          </p>
          <ul className="list-disc list-inside space-y-2 mt-2 text-gray-500">
            <li>Subscription fees are charged in advance and are non-refundable unless required by law</li>
            <li>You may cancel your subscription at any time; access continues until the end of the billing period</li>
            <li>We reserve the right to change pricing with reasonable notice</li>
            <li>Payments are processed by third-party payment providers</li>
          </ul>
        </Section>

        <Section title="8. Intellectual Property">
          <p>
            All content on CricketTips.ai — including AI-generated predictions, analysis, text, graphics, and code — is the intellectual property of CricketTips.ai. You may not reproduce, distribute, or use our content for commercial purposes without written permission.
          </p>
          <p>
            Cricket statistics and match data used in our analysis may be sourced from third-party data providers and are used in accordance with their respective terms.
          </p>
        </Section>

        <Section title="9. Limitation of Liability">
          <p>
            To the maximum extent permitted by applicable law, CricketTips.ai shall not be liable for:
          </p>
          <ul className="list-disc list-inside space-y-2 mt-2 text-gray-500">
            <li>Any financial losses resulting from acting on our predictions or analysis</li>
            <li>Losses incurred through betting or gambling activities</li>
            <li>Inaccuracies in AI-generated predictions or match analysis</li>
            <li>Interruption or unavailability of the site</li>
            <li>Actions of third-party bookmakers or affiliate partners</li>
          </ul>
          <p className="mt-2">
            Our total liability to you for any claim arising from use of the site shall not exceed the amount you paid us in the 30 days preceding the claim.
          </p>
        </Section>

        <Section title="10. Prohibited Use">
          <p>You agree not to:</p>
          <ul className="list-disc list-inside space-y-2 mt-2 text-gray-500">
            <li>Use the site if you are under 18 years of age</li>
            <li>Access the site from a jurisdiction where it is illegal to do so</li>
            <li>Scrape, copy, or redistribute our content without permission</li>
            <li>Attempt to reverse-engineer or interfere with our systems</li>
            <li>Use our predictions for match-fixing or any illegal activity</li>
            <li>Create multiple accounts to abuse free trial or promotional offers</li>
          </ul>
        </Section>

        <Section title="11. Governing Law">
          <p>
            These Terms & Conditions are governed by the laws of the <strong className="text-white">Republic of South Africa</strong>. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the South African courts.
          </p>
        </Section>

        <Section title="12. Contact">
          <p>For any questions regarding these terms:</p>
          <div className="mt-2 bg-gray-900 border border-gray-800 rounded-xl p-4 space-y-1">
            <p><strong className="text-white">CricketTips.ai</strong></p>
            <p>Email: <strong className="text-emerald-400">legal@crickettips.ai</strong></p>
            <p>Website: <strong className="text-white">crickettips.ai</strong></p>
          </div>
        </Section>

        <div className="mt-8 pt-6 border-t border-gray-800 flex items-center justify-between">
          <Link href="/" className="text-emerald-400 text-sm hover:text-emerald-300 transition-colors">← Back to Home</Link>
          <Link href="/privacy" className="text-gray-500 text-sm hover:text-white transition-colors">Privacy Policy →</Link>
        </div>
      </div>
    </div>
  )
}
