import { defineField, defineType } from 'sanity'

export const postType = defineType({
  name: 'post',
  title: 'Post',
  type: 'document',
  groups: [
    { name: 'content', title: 'Content', default: true },
    { name: 'seo', title: 'SEO' },
    { name: 'meta', title: 'Meta' },
  ],
  fields: [
    defineField({
      name: 'title',
      type: 'string',
      group: 'content',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      group: 'content',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      rows: 3,
      group: 'content',
      description: 'Short summary shown on blog listing cards',
    }),
    defineField({
      name: 'featuredImage',
      type: 'image',
      options: { hotspot: true },
      group: 'content',
      fields: [{ name: 'alt', type: 'string', title: 'Alt text' }],
    }),
    defineField({
      name: 'categories',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'category' }] }],
      group: 'content',
    }),
    defineField({
      name: 'publishedAt',
      type: 'datetime',
      initialValue: () => new Date().toISOString(),
      group: 'content',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'body',
      type: 'blockContent',
      group: 'content',
    }),
    // ── SEO ──
    defineField({
      name: 'seoTitle',
      title: 'SEO Title',
      type: 'string',
      group: 'seo',
      validation: (r) => r.max(60).warning('Keep under 60 chars for best SEO'),
    }),
    defineField({
      name: 'seoDescription',
      title: 'Meta Description',
      type: 'text',
      rows: 3,
      group: 'seo',
      validation: (r) => r.max(160).warning('Keep under 160 chars'),
    }),
    defineField({
      name: 'seoKeywords',
      title: 'Keywords',
      type: 'array',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      group: 'seo',
    }),
    // ── Meta ──
    defineField({
      name: 'source',
      title: 'Original Source',
      type: 'url',
      group: 'meta',
      description: 'Link to the original news article (for reference only)',
    }),
    defineField({
      name: 'autoGenerated',
      title: 'Auto-Generated',
      type: 'boolean',
      initialValue: false,
      group: 'meta',
    }),
  ],
  preview: {
    select: { title: 'title', media: 'featuredImage', date: 'publishedAt' },
    prepare({ title, media, date }) {
      return {
        title,
        media,
        subtitle: date ? new Date(date).toLocaleDateString() : 'Draft',
      }
    },
  },
})
